# Generated by Django 2.0.3 on 2018-11-20 18:22

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('description', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=50)),
                ('cant', models.PositiveSmallIntegerField(default=1)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Viveres'), (2, 'Frigorifico'), (3, 'Enlatados')])),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=200)),
                ('tw', models.CharField(max_length=50, null=True)),
                ('fb', models.CharField(max_length=50, null=True)),
                ('google', models.CharField(max_length=50, null=True)),
                ('rif', models.CharField(max_length=50)),
                ('localphone', models.CharField(max_length=50, null=True)),
                ('reference', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseConfirmation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('confirmation', models.PositiveSmallIntegerField(default=2)),
                ('start_date', models.DateTimeField(null=True)),
                ('cant_product', models.PositiveSmallIntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comprado', to='maracay.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_confirm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='purchaseHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_purchase', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantshopping', models.PositiveSmallIntegerField(default=0)),
                ('code', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to='maracay.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_shopping', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenPassword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costoenvio', models.PositiveSmallIntegerField(default=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
