# Generated by Django 2.0.3 on 2018-11-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0002_auto_20181120_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='total_purchase',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='total',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
    ]
