# Generated by Django 2.0.3 on 2018-07-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Viveres'), (2, 'Frigorifico'), (3, 'Enlatados')], default=int),
            preserve_default=False,
        ),
    ]
