# Generated by Django 2.0.3 on 2018-09-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0003_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costoenvio', models.PositiveSmallIntegerField(default=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
