# Generated by Django 2.0.3 on 2018-11-08 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maracay', '0005_auto_20181108_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseconfirmation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comprado', to='maracay.Product'),
        ),
        migrations.AlterField(
            model_name='purchaseconfirmation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_confirm', to=settings.AUTH_USER_MODEL),
        ),
    ]
